export const GOAL_LABELS: Record<string, string> = {
  overseas_expansion: "Overseas Expansion",
  automation: "Automation",
  process_improvement: "Process Improvement",
  new_product_development: "New Product Development",
  innovation: "Innovation",
  hiring: "Hiring",
  reskilling: "Reskilling",
  job_redesign: "Job Redesign",
  workforce_transformation: "Workforce Transformation",
  training: "Training",
  digital_transformation: "Digital Transformation",
  software_build: "Software / Digital Build",
  certification: "Certification",
  compliance: "Compliance",
  market_readiness: "Market Readiness",
  "r&d": "R&D",
  technology_development: "Technology Development",
};
